### ISSUE TITLE
Combine docker-compose

### ISSUE THREAD

**Issue by ThomasThelen** [rhizomik/rhizomerAPI#20]
Love this project! I noticed that there are two docker-compose files, one for the frontend and another for the backend. Would it be possible to combine both into a single docker-compose? Since each compose file only has one service-they're not taking full advantage of docker-compose's features like networking and single-command deployments. Using two docker-compose files might be considered anti-pattern because it's rejecting the idea of combining/composing docker deployments together.

I'm running the two services in a combined docker-compose locally, which I'd be more than happy to provide!

**Comment by rogargon** [comment]
Thanks @ThomasThelen. We have a separate docker-compose for each service because the backend is not tied to RhizomerEye frontend, other frontends are also possible. In any case, the RhizomerEye repo includes and example of a docker-compose including both services: https://github.com/rhizomik/rhizomerEye/blob/master/docker-compose.aws.yml

**Comment by ThomasThelen** [comment]
Ah I totally ignored that since I usually don't deploy on AWS-but you're right that it has both services and will work locally! Thanks!
